seata:
  enabled: true
  registry:
    type: nacos
    nacos:
      namespace: eed4a53a-2ee3-482e-ae60-de29641557fe
      group: DEFAULT_GROUP
      server-addr: localhost:8848
  config:
    type: nacos
    nacos:
      namespace: eed4a53a-2ee3-482e-ae60-de29641557fe
      group: DEFAULT_GROUP
      server-addr: localhost:8848
  tx-service-group: default_tx_group
server:
  port: 8081
spring:
  jpa:
    show-sql: true
  application:
    name: order
  cloud:
    nacos:
      config:
        namespace: eed4a53a-2ee3-482e-ae60-de29641557fe
        server-addr: localhost:8848
      discovery:
        namespace: eed4a53a-2ee3-482e-ae60-de29641557fe
        server-addr: localhost:8848
  config:
    import: nacos:order.yaml?refresh=true